name: Connect to VPN and SSH

on:
  push:
    branches:
      - main

jobs:
  connect_vpn_and_ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OpenConnect and SSHpass
        run: |
          sudo apt-get update
          sudo apt-get install -y openconnect sshpass

      - name: Connect to VPN in background
        id: vpn_connection
        run: |
          sudo bash -c "echo '${{ secrets.VPN_PASSWORD }}' | openconnect --background --user=${{ secrets.VPN_PASSWORD }} devnetsandbox-usw1-reservation.cisco.com:20212 --passwd-on-stdin"
        
      - name: Wait for VPN to connect
        run: |
          echo "Waiting for VPN connection..."
          for i in {1..10}; do
            if ifconfig | grep tun0; then
              echo "VPN is connected"
              break
            fi
            echo "VPN not connected yet, retrying in 5 seconds..."
            sleep 5
          done
          if ! ifconfig | grep tun0; then
            echo "VPN connection failed"
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Create virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Run Python script
        run: |
          source .venv/bin/activate
          python3 monitor_api/main.py
          python3 parsers/parse_health_response.py

      - name: Disconnect VPN
        if: always()
        run: |
          sudo pkill openconnect || echo "VPN already disconnected"
